controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\PasswordResetRequestForm;
use app\models\ResetPasswordForm;
use app\models\SignupAdminForm;
use app\models\SignupStudentForm;
use app\models\SignupTeacherForm;
use app\models\User;
use app\models\VerifyEmailForm;
use DateTime;
use InvalidArgumentException;
use Yii;
use yii\base\InvalidParamException;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\SignupForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'about'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['about'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return User::isUserAdmin(Yii::$app->user->identity->username);
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
//            'error' => [
//                'class' => 'yii\web\ErrorAction',
//            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if(!Yii::$app->user->isGuest){
            if (User::isUserStudent(Yii::$app->user->identity->username)) {
                $this->redirect(array(
                    'student-test/index',
                    'status' => 'notpassed'
                ));
            }
            if (User::isUserAdmin(Yii::$app->user->identity->username) || User::isUserTeacher(Yii::$app->user->identity->username)) {
                $this->redirect(array(
                    'test/index'
                ));
            }
        }

        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionGetServerTime()
    {
        $now = new DateTime();
        echo $now->format("M j, Y H:i:s O");
    }

    public function actionSignup()
    {
        $model = new SignupForm();

        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('passwordResetRequestForm', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');
            return $this->goHome();
        }

        return $this->render('resetPasswordForm', [
            'model' => $model,
        ]);
    }

    /**
     * Signs amin up.
     *
     * @return mixed
     */
    public function actionSignupAdmin()
    {
        $model = new SignupAdminForm();
        $role = "Администратор";
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Thank you for registration as Admin. Please check your inbox for verification email.');
            return $this->goHome();
        }

        return $this->render('signup', [
            'model' => $model,
            'role'  => $role,
        ]);
    }

    /**
     * Signs teacher up.
     *
     * @return mixed
     */
    public function actionSignupTeacher()
    {
        $model = new SignupTeacherForm();
        $role = "Переподаватель";
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Thank you for registration as Teacher. Please check your inbox for verification email.');
            return $this->goHome();
        }

        return $this->render('signup', [
            'model' => $model,
            'role'  => $role,
        ]);
    }

    /**
     * Signs Student up.
     *
     * @return mixed
     */
    public function actionSignupStudent()
    {
        $model = new SignupStudentForm();
        $role = "Студент";
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Thank you for registration as Student. Please check your inbox for verification email.');
            return $this->goHome();
        }

        return $this->render('signup', [
            'model' => $model,
            'role'  => $role,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @throws BadRequestHttpException
     * @return yii\web\Response
     */
    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($user = $model->verifyEmail()) {
            if (Yii::$app->user->login($user)) {
                Yii::$app->session->setFlash('success', 'Your email has been confirmed!');
                return $this->goHome();
            }
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }


    public function actionError()
    {
        if ($error = Yii::$app->errorHandler->exception) {
            if (Yii::$app->request->isAjax) {
                echo $error['message'];
            } else {
                $defaultMessage = 'Сервис временно испытывает проблемы. Приносим извинения за временные неудобства.';

                $layout = 'error';

                switch ($error->statusCode) {
                    case '404':
                        $layout = 'error404';
                        break;
                    /*
                    case '500':
                        $error['message'] = $defaultMessage;
                        break;
                    case '400':
                        $error['message'] = 'Запрос введеный вами некорректен. Пожалуйста, убедитесь в его правильности.';
                        break;
                    case '403':
                        $message = $error->getMessage();
//                        $error['message'] = 'У вас нет прав доступа на эту страницу.';
                        break;
                    default:
                        $error['message'] = 'Возникла непредвиденная ошибка. Приносим извинения за временные неудобства.';
                        break;
                    */
                }

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

use app\controllers\SiteController;
use yii\helpers\Html;


/* @var $this SiteController */
/* @var $error array */

$this->title=Yii::$app->name . ' - Error';
if($code == 403) {
	$messageHeader = 'Отказано в доступе';
} else {
	$messageHeader = "Ошибка {$code}";
}

?>
<h2><?= $messageHeader ?></h2>

<div class="error">
<?php echo Html::encode($message); ?>
</div>
<div class="contact-admin">
    Электронный адрес для связи с администрацией: <?= Html::a(Yii::$app->params['adminEmail'], array('site/contact')); ?>.
</div>

views/site/error404.php
<link href="<?= Yii::$app->request->baseUrl ?>/css/svg-404.css" rel="stylesheet">
    <script src="<?= Yii::$app->request->baseUrl ?>/js/svgError.js"></script>
    
    <div class="error-wrapper">
      <h1>Страница не найдена</h1>
      <div class="error-message">
        <p>Страница, которую вы искали не была найдена. Пожалуйста, удостоверьтесь в правильности ссылки введенной вами в адресной строке браузера.</p>
      </div>
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="60%" height="60%" viewBox="-50 0 697.6 266.4" class="line-animated">
          <path d="M123.689,254.399V188.54H11.95v-21.089L119.249,13.903h35.149
            v149.478h33.67v25.159h-33.67v65.859H123.689z M123.689,163.381V83.092c0-12.58,0.37-25.16,1.11-37.74h-1.11
            c-7.4,14.06-13.32,24.42-19.98,35.52L44.88,162.641v0.74H123.689z
            M289.443,258.47c-46.989,0-79.179-44.029-79.918-123.578
            c0-81.029,35.149-125.059,83.988-125.059c50.319,0,79.549,45.14,79.549,121.729c0,81.769-30.709,126.908-83.249,126.908H289.443z
            M291.293,233.31c32.93,0,48.839-38.85,48.839-100.268c0-59.199-14.8-98.049-48.839-98.049c-29.6,0-48.84,37.74-48.84,98.049
            c-0.739,62.529,18.5,100.268,48.47,100.268H291.293z
            M503.297,254.399V188.54H391.559v-21.089L498.858,13.903h35.149
            v149.478h33.67v25.159h-33.67v65.859H503.297z M503.297,163.381V83.092c0-12.58,0.37-25.16,1.11-37.74h-1.11
            c-7.399,14.06-13.319,24.42-19.979,35.52l-58.829,81.769v0.74H503.297z
            "
            stroke="#0C0B08"
            stroke-width="3"
            fill="none"
            stroke-dasharray="988.01 988.01"
            stroke-dashoffset="0">
          </path>
        </svg>
    </div>

views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">
    <div class="main-page-intro text-center">
        <?php if(Yii::$app->session->hasFlash('success')):?>
            <div class="alert alert-success">
                <?php echo Yii::$app->session->getFlash('success'); ?>
            </div>
        <?php endif; ?>
        <h1>TestHub</h1>
        <div class="th-info">
            <p>Сервис позволяет проверять знания студентов в автоматическом режиме с помощью тестов. Зарегистрируйтесь, чтобы принять участие.</p>
            <div class="main-register-pics">
                <a class="main-student-pic" href="<?= Yii::$app->urlManager->createUrl('site/signup-student')?>"><img title="Регистрация студента" src="<?= Yii::$app->request->baseUrl?>/img/student_pic.png" style="width: 22% !important;"></a>
                <a class="main-teacher-pic" href="<?= Yii::$app->urlManager->createUrl('site/signup-teacher')?>"><img title="Регистрация преподавателя" src="<?= Yii::$app->request->baseUrl?>/img/teacher_pic.png" style="width: 30% !important;"="30%"></a>
            </div>
        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">

    <div class="row">
        <div class="col-lg-4">
            <p>Введите свое имя пользователя и пароль, указанный при регистрации:</p>
        </div>
    </div>

    <?php $form = ActiveForm::begin([
        'layout'=>'horizontal',
        'options' => ['class' => 'signup-form form-register1'],
        'fieldConfig' => [
            'template' => "{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
            'horizontalCssClasses' => [
                'label' => 'col-sm-4',
                'offset' => 'col-sm-offset-4',
                'wrapper' => 'col-sm-4',
                'error' => '',
                'hint' => '',
            ],
        ],
    ]); ?>

        <div class="row">
            <?= $form->field($model, 'username')->textInput(['autofocus' => true, 'placeholder' => 'Ваше имя', 'class'=>'form-control text-center']) ?>
        </div>

        <div class="row">`
            <?= $form->field($model, 'password')->passwordInput(['placeholder' => 'Ваше пароль', 'class'=>'form-control text-center']) ?>
        </div>

        <div class="row rememberMe">
            <?= $form->field($model, 'rememberMe')->checkbox([
                'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
            ]) ?>
        </div>
        <div class="row forgot">
            <div class="form-group field-forgot text-left">
                <div style="color:#999;/*margin:1em 0;*/display: flex;" class="col-lg-offset-1 col-lg-3 text-center">
                    <?= Html::a('Забыли пароль?', ['site/request-password-reset']) ?>.
                </div>
                <div class="div col-lg-8">

                </div>
            </div>
        </div>
        <div class="row buttons">
            <div class="form-group">
                <div class="col-lg-offset-1 col-lg-11">
                    <?= Html::submitButton('Войти', ['class' => 'login-button', 'name' => 'login-button']) ?>
                </div>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/passwordResetRequestForm.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Please fill out your email. A link to reset password will be sent there.</p>
    <div class="row">
        <div class="col-lg-5">

            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>
            <div class="form-group">
                <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
            </div>
            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

views/site/resetPasswordForm.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Please choose your new password:</p>
    <div class="row">
        <div class="col-lg-5">

            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
            <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>
            <div class="form-group">
                <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
            </div>
            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

views/site/signup.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $role string */

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <div class="row">
        <div class="col-lg-4">
            <p>Заполните следующие поля что бы зарегистрироваться как <?= $role; ?>:</p>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">

            <?php $form = ActiveForm::begin([
                'id' => 'form-signup',
                'layout'=>'horizontal',
                'options' => ['class' => 'signup-form form-register1'],
                'fieldConfig' => [
                    'template' => "{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                    'horizontalCssClasses' => [
                        'label' => 'col-sm-4',
                        'offset' => 'col-sm-offset-4',
                        'wrapper' => 'col-sm-4',
                        'error' => '',
                        'hint' => '',
                    ],
                ],
            ]); ?>
            <div class="row">
                <?= $form->field($model, 'username')->textInput(['autofocus' => true, 'placeholder' => 'Ваше имя', 'class'=>'form-control text-center']) ?>
            </div>
            <div class="row">
                <?= $form->field($model, 'email')->textInput(['autofocus' => true, 'placeholder' => 'Ваше email', 'class'=>'form-control text-center']) ?>
            </div>
            <div class="row">
                <?= $form->field($model, 'password')->passwordInput(['placeholder' => 'Ваше имя', 'class'=>'form-control text-center']) ?>
            </div>
            <div class="row buttons">
                <div class="form-group col-sm-4 text-center">
                    <?= Html::submitButton('Зарегистрироваться', ['class' => 'signup-button', 'name' => 'signup-button']) ?>
                </div>
            </div>
            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>